feature/GDEV-151
ghga-de/sandbox-storage pull request #33
Opened 2021-08-18 14:37 UTC by ac-jorellanaf

2021-08-18 15:31 UTC, MoritzHahn1337 requested changes
Looks good, once you fixed the checks

2021-08-19 08:55 UTC, KerstenBreuer approved these changes
same here 👍

2021-08-19 13:39 UTC, ac-jorellanaf commented
Not sure what the problem is at all.

2021-08-19 14:03 UTC, KerstenBreuer commented
The Github actions workflow used the wrong Python version. The chassis lib is only available for 3.9+. Just fixed it.

2021-08-19 14:06 UTC, KerstenBreuer requested changes

2021-08-19 14:06 UTC, KerstenBreuer commented on setup.py
> +    "ghga-service-chassis-lib==0.3.0",
```suggestion
    "ghga-service-chassis-lib[pubsub]==0.3.0",
```

I think we need the pubsub extra don't we?

2021-08-19 14:07 UTC, ac-jorellanaf commented on setup.py
> +    "ghga-service-chassis-lib==0.3.0",
Yes. It was an attempt at a fix on my end.

2021-08-19 14:09 UTC, KerstenBreuer approved these changes
Only this minor change

2021-08-19 14:09 UTC, KerstenBreuer commented on setup.py
> +    "pika==1.2.0",
```suggestion
```

Oh and this can be removed then, as it's already in the shared lib.

2021-08-19 14:12 UTC, KerstenBreuer commented
Can be merged @MoritzHahn1337?

2021-08-19 14:16 UTC, MoritzHahn1337 approved these changes

2021-08-19 14:20 UTC, merged