GDEV-97: Add documentation
ghga-de/sandbox-storage pull request #42
Opened 2021-08-30 16:03 UTC by deepakunni3

This PR tidies docstrings and adds Mkdocs YAML for autogenerating documentation.

2021-09-02 09:05 UTC, ac-jorellanaf approved these changes

2021-09-02 09:11 UTC, ac-jorellanaf requested changes
Fix the SCA issues first.

2021-09-06 14:30 UTC, ac-jorellanaf submitted a review, later dismissed

2021-09-07 07:37 UTC, alamgirmani approved these changes

2021-09-07 07:38 UTC, merged